### ISSUE TITLE
exception in plugin git flow integration plus (0.8.0)

### ISSUE THREAD

**Issue by shuohao** [RubinCarter/gitflow4idea-fix#37]
java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:128)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:126)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:83)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:126)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:121)
	at com.intellij.execution.wsl.WslIjentUtil.runProcessBlocking(WslIjentUtil.kt:62)
	at com.intellij.execution.wsl.WSLDistribution.lambda$patchCommandLine$2(WSLDistribution.java:239)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:490)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:463)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:356)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:86)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:55)
	at git4idea.commands.GitTextHandler$MyOSProcessHandler.<init>(GitTextHandler.java:146)
	at git4idea.commands.GitLineHandler$1.<init>(GitLineHandler.java:143)
	at git4idea.commands.GitLineHandler.createProcess(GitLineHandler.java:143)
	at git4idea.commands.GitTextHandler.startProcess(GitTextHandler.java:76)
	at git4idea.commands.GitHandler.start(GitHandler.java:469)
	at git4idea.commands.GitHandler.runInCurrentThread(GitHandler.java:407)
	at git4idea.commands.GitImplBase.doRun(GitImplBase.java:199)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:171)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:62)
	at git4idea.config.GitConfigUtil.getValue(GitConfigUtil.java:82)
	at git4idea.config.GitConfigUtil.getValue(GitConfigUtil.java:75)
	at gitflow.GitflowConfigUtil.lambda$update$2(GitflowConfigUtil.java:82)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

idea version: 2024.1

**Comment by bartdigitalpulse** [comment]
Having the same issue in phpstorm 2024.3


```
java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable$lambda$0(coroutines.kt:142)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:85)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:140)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:123)
	at com.intellij.execution.wsl.WslIjentUtil.runProcessBlocking(WslIjentUtil.kt:68)
	at com.intellij.execution.wsl.WSLDistribution.lambda$patchCommandLine$2(WSLDistribution.java:245)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:463)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:469)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:374)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:55)
	at git4idea.commands.GitTextHandler$MyOSProcessHandler.<init>(GitTextHandler.java:166)
	at git4idea.commands.GitLineHandler$1.<init>(GitLineHandler.java:143)
	at git4idea.commands.GitLineHandler.createProcess(GitLineHandler.java:143)
	at git4idea.commands.GitTextHandler.startProcess(GitTextHandler.java:77)
	at git4idea.commands.GitHandler.start(GitHandler.java:470)
	at git4idea.commands.GitHandler.runInCurrentThread(GitHandler.java:408)
	at git4idea.commands.GitImplBase.doRun(GitImplBase.java:199)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:171)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:62)
	at git4idea.config.GitConfigUtil.getValue(GitConfigUtil.java:88)
	at git4idea.config.GitConfigUtil.getValue(GitConfigUtil.java:75)
	at git4idea.repo.GitProjectConfigurationCache.readRepositoryConfig$lambda$1(GitConfigurationCache.kt:59)
	at git4idea.repo.GitConfigurationCacheBase.computeCachedValue(GitConfigurationCache.kt:116)
	at git4idea.repo.GitProjectConfigurationCache.readRepositoryConfig(GitConfigurationCache.kt:57)
	at git4idea.config.gpg.GitGpgConfigUtilsKt.isGpgSignEnabledCached(GitGpgConfigUtils.kt:89)
	at git4idea.commit.signing.GpgAgentConfigurator$Companion.isEnabled(GpgAgentConfigurator.kt:69)
	at git4idea.commit.signing.GpgAgentConfigurator.isEnabled(GpgAgentConfigurator.kt)
	at git4idea.commands.GitHandlerAuthenticationManager.prepareGpgAgentAuth(GitHandlerAuthenticationManager.java:191)
	at git4idea.commands.GitHandlerAuthenticationManager.lambda$prepare$0(GitHandlerAuthenticationManager.java:71)
	at git4idea.GitUtil.tryRunOrClose(GitUtil.java:1031)
	at git4idea.commands.GitHandlerAuthenticationManager.prepare(GitHandlerAuthenticationManager.java:68)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:160)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:62)
	at gitflow.GitflowImpl.version(GitflowImpl.java:504)
	at gitflow.GitflowVersionTester.init(GitflowVersionTester.java:69)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:304)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```
