### ISSUE TITLE
`ActionUpdateThread.OLD_EDT` is deprecated

### ISSUE THREAD

**Issue by FedericoBartolini** [RubinCarter/gitflow4idea-fix#38]
* **I'm submitting a feature request

* **What is the current behavior?**
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'gitflow.actions.StartBugfixAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: Gitflow-Fix]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**
1. Open IntelliJ
* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.13
  - Gitflow version: 1.12.3
  
- IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to Federico Bartolini
Subscription is active until October 11, 2024.
For educational use only.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (241.14494.150)
  com.intellij.ml.llm (241.14494.240)
  Gitflow-Fix (0.7.13)
Kotlin: 241.14494.240-IJ

**Comment by BrunoBerck** [comment]
Same problem with PHPStorm 2024.1

Build #PS-241.14494.237, built on March 27, 2024
Licensed to ********
Subscription is active until January 31, 2025.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.8.4-200.fc39.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
Non-Bundled Plugins:
  net.sjrx.intellij.plugins.systemdunitfiles (223.240127.136)
  com.jetbrains.space (241.14494.150)
  com.vecheslav.darculaDarkerTheme (1.2.0)
  com.intellij.ml.llm (241.14494.320)
  Gitflow-Fix (0.7.13)
  ru.adelf.idea.dotenv (2024.1)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (10.0.0)
  mobi.hsz.idea.gitignore (4.5.3)
  de.espend.idea.php.phpunit (7.1)
Current Desktop: GNOME

**Comment by MondaySam** [comment]
Same issue when Starting or Finishing a Release:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'gitflow.actions.StartFeatureAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: Gitflow-Fix]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by TobiasWeis** [comment]
Same issue with intellij 2024.2.3 Community Edition

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'gitflow.actions.StartFeatureAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: Gitflow-Fix]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by xeader** [comment]
Same issue:

```
PhpStorm 2024.2.3
Build #PS-242.23339.16, built on September 25, 2024
Licensed to *************
Subscription is active until July 20, 2025.
Runtime version: 21.0.4+13-b509.17 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.windowSystem.autoShowProcessPopup=true
  ide.balloon.shadow.size=0
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  vcs.log.index.enable=true
  documentation.show.toolbar=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  i18n.locale=
  js.debugger.webconsole=false
Non-Bundled Plugins:
  org.toml.lang (242.20224.155)
  com.intellij.ideolog (242.23339.18)
  String Manipulation (9.14.1)
  Key Promoter X (2024.2.0)
  org.intellij.RegexpTester (2.2.0)
  com.chuntung.plugin.gistsnippet (1.2.0)
  net.seesharpsoft.intellij.plugins.csv (4.0.0)
  Gitflow-Fix (0.7.13)
  com.github.aleksandrsl.intellijbrowserslist (1.0.2)
  com.nekofar.milad.intellij.nuxtjs (2.1.1)
  tv.twelvetone.intellij.plugins.intellivue (1.2.16)
  com.kalessil.phpStorm.phpInspectionsEA (5.1.0)
  ru.adelf.idea.dotenv (2024.2.1)
  com.dryabov.phpStorm.phpregexp (0.9.7)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (11.1.0)
  mobi.hsz.idea.gitignore (4.5.4)

```

**Comment by ZeroDifa** [comment]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'gitflow.actions.TrackFeatureAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: Gitflow-Fix]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by Alik2607** [comment]
com.intellij.diagnostic.PluginException: ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon. 'gitflow.actions.TrackFeatureAction' must override getActionUpdateThread() and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: Gitflow-Fix]
at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

Noticed this error only happens when you use Intellij 2024.2+ versions. Works fine with 2024.1.7 as of now

**Comment by MondaySam** [comment]
I checked the code: The fix is already implemented on develop (27.07.23), however, the master branch and last release are from 25.07.23.

So all that's missing is a new release.

**Comment by phunni** [comment]
Came here to report this - glad to see it's already in hand :-)
